### ISSUE TITLE
Profile Pics [Google Signin]

### ISSUE THREAD

**Issue by herrye991** [dickyrey/kumparan_clone#2]
![IMG_20230126_152449](https://user-images.githubusercontent.com/42521692/214789092-a9279a67-9f81-4e18-aebb-245e2f4f542a.jpg)

**Comment by dickyrey** [comment]
Problem solved

![Screenshot_20230126-174547](https://user-images.githubusercontent.com/42982286/214817421-b502ed6a-a0e2-4269-b8e2-9f64d6d63da7.png)
