### ISSUE TITLE
Add Confirmation [Signout]

### ISSUE THREAD

**Issue by herrye991** [dickyrey/kumparan_clone#3]
![Screenshot_20230126_152619](https://user-images.githubusercontent.com/42521692/214789415-060f1f1f-0eda-43c6-ae10-26ce8a4f5b3f.jpg)

**Comment by dickyrey** [comment]
Confirmation Sign out Dialog Created!

![image](https://user-images.githubusercontent.com/42982286/214818702-68e9ecad-090c-4a61-8a34-0de88ad11f58.png)
